import type { CampaignBrief } from "@/lib/brief/types"

export function exportBriefAsJSON(brief: CampaignBrief): string {
  return JSON.stringify(brief, null, 2)
}

function joinList(values: string[], fallback = "None"): string {
  return values.length > 0 ? values.join(", ") : fallback
}

function formatOptional(value: string | null | undefined, fallback: string): string {
  return value && value.trim().length > 0 ? value : fallback
}

function formatBoolean(value: boolean): string {
  return value ? "Yes" : "No"
}

export function exportBriefAsMarkdown(brief: CampaignBrief): string {
  const warningBlock = brief.meta.audienceWarning
    ? `\n> **Warning:** ${brief.meta.audienceWarning}\n`
    : ""

  const missingInfoBlock =
    brief.missingInfoQuestions && brief.missingInfoQuestions.length > 0
      ? [
          "*Missing information required before publishing:*",
          ...brief.missingInfoQuestions.map((question) => `- ${question}`),
          "",
        ].join("\n")
      : ""

  const messagingPillars = brief.messagingPillars
    .map(
      (pillar) => `### ${pillar.pillar}

**Do:**
${pillar.do.map((item) => `- ${item}`).join("\n")}

**Avoid:**
${pillar.avoid.map((item) => `- ${item}`).join("\n")}
`
    )
    .join("\n")

  const contentThemes = brief.contentThemes
    .map((theme, index) => `${index + 1}. ${theme}`)
    .join("\n")

  const experiments =
    brief.experimentPlan.length > 0
      ? brief.experimentPlan
          .map((experiment) => {
            const name = experiment.name || experiment.id
            const description = experiment.hypothesis || "Details available in strategy intake."
            return `- **${name}:** ${description}`
          })
          .join("\n")
      : "No experiments planned for this brief."

  const requiredAssets = brief.requiredAssets
    .map((asset) => `| ${asset.assetType} | ${asset.owner} |`)
    .join("\n")

  const successSignals = brief.successSignals.map((signal) => `- ${signal}`).join("\n")

  const claimsCautions = brief.complianceNotes.claimsCautions
    .map((caution) => `- ${caution}`)
    .join("\n")

  const constraints = brief.constraints.map((constraint) => `- ${constraint}`).join("\n")

  return `# Campaign Brief: ${brief.title}

**Generated:** ${brief.meta.generatedAt}
**Brief Version:** ${brief.meta.brief_version}
**Engine Version:** ${brief.meta.engine_version}
**Confidence Score:** ${brief.meta.confidenceScore}/100
**Audience Clarity:** ${brief.meta.stakeholdersClarityLevel}${warningBlock}

---

## Program Overview

**Program Summary**
${brief.programSummary}

**Primary Audience**
${brief.primaryAudience}
${missingInfoBlock}
**Secondary Audience**
${formatOptional(brief.secondaryAudience, "Not applicable")}

**Positioning Statement**
${brief.positioningStatement}

---

## Messaging Pillars

${messagingPillars}

---

## Tone Profile

| Dimension | Score (0-10) |
|-----------|--------------|
| Calm | ${brief.toneProfile.calm} |
| Upbeat | ${brief.toneProfile.upbeat} |
| Formal | ${brief.toneProfile.formal} |

**Tone Tags:** ${joinList(brief.toneProfile.tags)}

---

## Content Themes

${contentThemes}

---

## Channel and Cadence Plan

**Channels:** ${joinList(brief.channelPlan)}

**Cadence Frequency:** ${brief.cadencePlan.frequency}

**Cadence Rationale:** ${brief.cadencePlan.rationale}

---

## Experiment Plan

${experiments}

---

## Required Assets

| Asset Type | Owner |
|------------|-------|
${requiredAssets}

---

## Success Signals

${successSignals}

---

## Compliance Notes

**Requires Visibility Archive:** ${formatBoolean(
    brief.complianceNotes.requiresVisibilityArchive
  )}
**Requires Approval Workflow:** ${formatBoolean(
    brief.complianceNotes.requiresApprovalWorkflow
  )}

**Claims Cautions:**
${claimsCautions}

---

## Constraints

${constraints}

---

*This brief was generated by Marketing OS Campaign Brief Engine v${brief.meta.engine_version}.*
*Brief version ${brief.meta.brief_version} - ${brief.meta.generatedAt}*
`
}

export function buildClipboardPayload(prompt: string, label: string): string {
  return `=== ${label} ===

${prompt}

=== End of ${label} ===`
}

export function generateExportFilename(
  brief: CampaignBrief,
  extension: "json" | "md"
): string {
  const rawSlug = brief.title
    .toLowerCase()
    .replace(/[^a-z0-9\\s-]/g, "")
    .replace(/\\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")

  const basePrefix = "campaign-brief-"
  const versionSuffix = `-v${brief.meta.brief_version}.${extension}`
  const maxLength = 80
  const maxSlugLength = Math.max(8, maxLength - basePrefix.length - versionSuffix.length)
  const slug = rawSlug.length > maxSlugLength ? rawSlug.slice(0, maxSlugLength) : rawSlug
  return `${basePrefix}${slug}${versionSuffix}`
}
